name: Tino Space
favicon: null
layout_spectrum: 0.24595
typography_spectrum: 0.9955
title: The new age in interactive chat promotions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5b5b5b'
    - '#cccccc'
    - '#343434'
    - '#fcfcfc'
  brandStrength: 0.5
  lightness: 0.3090636602137238
  saturation: 0.36573946522548795
  rhythmicContrast: 0.21509157284162939
purpose: []
