typography_spectrum: 0.9955
color:
  brandColors:
    - '#e00000'
    - '#b0b3bb'
    - '#560000'
    - '#ffffff'
    - '#ff805a'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.36573946522548795
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24595
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/faec3918-61ef-4118-aaf5-c9ed2c12a770.png
name: Tino Space
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Tino Space: The new age in interactive chat promotions'
description: 'Meet My Friends: Diva, MyCha, Chef and B3zzzCaruzo'
purpose: []
