name: Tino Space
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9955
title: The new age in interactive chat promotions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e00000'
    - '#b0b3bb'
    - '#560000'
    - '#ffffff'
    - '#ff805a'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.36573946522548795
  rhythmicContrast: 0.5
purpose: []
