name: Tino Space
favicon: null
layout_spectrum: 0.24595
typography_spectrum: 0.9955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfffe'
    - '#000000'
    - '#a0a1a3'
    - '#2d2e30'
    - '#4e4f51'
  brandStrength: 0.5
  lightness: 0.3090636602137238
  saturation: 0.36573946522548795
  rhythmicContrast: 0.21509157284162939
purpose: []
